[#licenses]
== Software Licenses

Todays IT industry heavily depends on the concept of sharing code. No non trivial application exists today which has no dependency on open source software. As soon as you turn on your computer or your mobile phone you are using a open source software of some form. Open source software is part of every relevant software stack today, it is the backone of our industry.

Every software engineer should be familiar with software licenses, this chapter gives an overview of the most important ones.

Software licenses greatly vary in their scope and meaning, the decision to choose which license has to be well thought of. Licenses protect intellectual property. They are a legal instrument which govern the use or redistribution of software.

A software license grants an end-user permission to use one or more copies of software in ways where such a use would otherwise potentially constitute copyright infringement of the software owner's exclusive rights under copyright law.

Below follows a nonexhaustive list of often used licenses. Disclaimer: this is a short summary of the original texts, and no legal advice. The enumeration serves as an entry point for this difficult topic. footnote:[The following subsections are quoted from https://choosealicense.com/licenses/[choosealicense.com] and https://tldrlegal.com[tldrlegal.com]]

=== GPL

This is the most license which you may have heard already, it is very popular and often is used as a synonym for 'open source' software. Many well known projects are licensed under GPL, the most prominent one is Linux, the operating system.

Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

Explained in a more accessible language:

 You may copy, distribute and modify the software as long as you track changes/dates in source files. Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.

Full text is available here: https://gnu.org/licenses/gpl.html

NOTE: GPL - like other licenses - are versioned. That means there is a GPL license, a GPLv2 and a GPLv3 license as of today. Although the main intent stays the same, there are subtle differences between those versions.

=== Apache 2.0 License

If you license your software under Apache 2.0 License, you can do what you like with the software, as long as you include the required notices. This permissive license contains a patent license from the contributors of the code. footnote:[https://www.apache.org/[The Apache Software Foundation] is an organisation which fosters open source projects. It was founded in 1999, originally to support the development of the Apache Web Server, a technology which is of paramount importance for the world wide web]

It is a permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

Full text is available here: http://www.apache.org/licenses/

=== BSD

The BSD 3-clause license allows you almost unlimited freedom with the software so long as you include the BSD copyright and license notice in it (found in Fulltext).

See https://opensource.org/licenses/BSD-3-Clause for the full text of this license.

=== MIT

From choosealicense.com:

A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

Full text: https://mit-license.org
