== Overview

This document contains the course material for a lecture held in 2017 at the *FH JOANNEUM - University of Applied Sciences* called **Software Engineering Basic**. 

This course helps undergraduate students to learn about basic principles of programming and software development. 

The implementation language is Scala, which lends itself well for various styles of programming. The students will make use of modern development environments and toolings and learn how to organize small software projects. 

One emphasis of the course is how to write tests. 

Furthermore, the course will cover several case studies to demonstrate various aspects of software development.

=== Contents

The course contains following subjects:

- <<sw-engineering>> : Definition, Discussion about Methodologies. Are we in a software crisis?
- <<toolings>> : Continuous Integration Server, Build Tools, Ticket Systems, Documentation Systems
- <<scala-basics>> : An introduction into the Scala programming language
- <<testing>> : What is the purpose of testing?
- Selected case studies to compare functional and imperative programming
- GUI programming: create event driven applications
- Server / Client programming with protocols
- link:../casestudies/index.html[Case Studies] Some case studies for applications

=== Organisational aspects

The course consists of lectures and labs. The latter serve for practicing the theory learned in the lectures, working on assignments and exercises. 

=== Grading

The course will have several homework assignments which will contribute to the overall score of the course. At the end of the course there will be a team project and a final (written) exam.

 

